### ISSUE TITLE
Invariant Violation: requireNativeComponent: "NVNavigationBar" was not found in the UI Manager

### ISSUE THREAD

**Issue by arunmenon1975** [grahammendick/navigation#260]
I am evaluating `navigation-react-native` as the routing solution for a simple app that i am creating. 

I am on a fresh install of React Native and the navigation libraries. I get the following invariant violation error when i try to run the redux example on the IoS simulator. 

![image](https://user-images.githubusercontent.com/2016484/60751854-aadfee80-9fda-11e9-99fa-cc19e8c8cac8.png)

my package.json has the following content:

```
{
  "name": "menunativenavigation",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "navigation": "^5.2.0",
    "navigation-react": "^4.1.1",
    "navigation-react-native": "^5.2.1",
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.0.1",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I am using Visual Studio Code and the normal run command `react-native run-ios`. I am trying to mirror exactly the redux example provided in the repo. 

My App.js file:

```
import React from 'react';
import {StateNavigator} from 'navigation';
import {NavigationHandler} from 'navigation-react';
import {NavigationStack} from 'navigation-react-native';
import {createStore} from 'redux';
import {Provider} from 'react-redux';
import reducer from './reducer';
import People from './People';
import Person from './Person';

const stateNavigator = new StateNavigator([
  {key: 'people'},
  {key: 'person', trackCrumbTrail: true},
]);

const {people, person} = stateNavigator.states;
people.renderScene = () => <People />;
person.renderScene = ({id}) => <Person id={id} />;

const store = createStore(reducer);
stateNavigator.navigate('people');
export default () => (
  <Provider store={store}>
    <NavigationHandler stateNavigator={stateNavigator}>
      <NavigationStack />
    </NavigationHandler>
  </Provider>
);
```

my index.js:

```
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

The People.js file:

```
import React from 'react';
import {ScrollView, FlatList} from 'react-native';
import {NavigationBarIOS} from 'navigation-react-native';
import {connect} from 'react-redux';
import PersonItem from './PersonItem';

const mapStateToProps = ({people: {allIds}}) => ({ids: allIds});

const People = ({ids}) => (
  <ScrollView contentInsetAdjustmentBehavior="automatic">
    <NavigationBarIOS title="People" />
    <FlatList
      data={ids}
      keyExtractor={id => id}
      renderItem={({item}) => <PersonItem id={item} />} />
  </ScrollView>
);

export default connect(mapStateToProps)(People);
```

The only difference i see is that the example has the React Native version at 0.59 while my install gets 0.60 and possibly barfs at some of the breaking changes that this version introduces. I just wanted to now if i will need to roll back to 0.59 until any update happens.

**Comment by grahammendick** [comment]
Thanks for trying out the Navigation router. 

Did you remember to link the `navigation-react-native` package?
```
react-native link navigation-react-native
```
Once I’ve made the React Native 0.60 changes you won’t have to link it anymore. Next release, I’ll update the [setup guide](https://grahammendick.github.io/navigation/documentation/native/setup.html) with the new instructions

**Comment by arunmenon1975** [comment]
Thanks for the quick response. 

I assumed that with v 0.60 having the `autolink` feature i wouldn't have to manually link so i just went ahead with the build as soon as i had all the packages and files in place. 

I just linked now but the build seems to fail in Visual Studio Code. I missed reading the error in full but it instructed to attempt opening the project in XCode which i proceeded to do. 

In XCode i noticed that (post manual linking via `react-native link navigation-react-native`) the 'Libraries' group was empty as well as there was no mention of a `navigation-react-native` specific `.a` file in the 'Link Binary with Libraries' setting.

I attempted a 'Add file' to Library and linked the `NavigatonReactNative.xcodeproj` from the ios directory in node_modules(`node_modules/navigation-react-native/ios/NavigatonReactNative.xcodeproj`. The `libNavigationReactNative.a` file now appears.  I ran a build but it seems to fails in XCode as well. 

An excerpt from the error log:
```
In file included from /Users/arunmenon/Sites/menunativenavigation/node_modules/navigation-react-native/ios/NVTabBarItemManager.m:1:
/Users/arunmenon/Sites/menunativenavigation/node_modules/navigation-react-native/ios/NVTabBarItemManager.h:1:9: fatal error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **


The following build commands failed:
	CompileC /Users/arunmenon/Sites/menunativenavigation/ios/build/menunativenavigation/Build/Intermediates.noindex/NavigationReactNative.build/Debug-iphonesimulator/NavigationReactNative.build/Objects-normal/x86_64/NVTabBarView.o /Users/arunmenon/Sites/menunativenavigation/node_modules/navigation-react-native/ios/NVTabBarView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

Perhaps i will try it out all over again on a fresh install (which is not a problem since i have not started on anything) and report back if i run into any issues.

**Comment by grahammendick** [comment]
I'll have a new version that works with React Native v0.60 and `autolinking` soon. Might be safest if you use v0.59 for now and manually link

**Comment by arunmenon1975** [comment]
ok. I will go with `v0.59` for now. Most of the other functionalities that i depend on(`react-native-firebase `etc) haven't moved reliably to `v0.60` as well - some are in alpha and most others may require some additional tinkering and research - so it should be fine for me. 

I am closing this issue and looking forward to the official v0.60-compatible update sometime later.

**Comment by grahammendick** [comment]
Thanks. I'll let you know in this issue when the v0.60-compatible update comes out. It won't be long

**Comment by arunmenon1975** [comment]
As an update for anybody reading this, i got it going perfectly well without any issues with `v0.59.10`(the latest in the 0.59 branch).  This is my current package.json:

```
{
  "name": "menunativenavigation",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "navigation": "^5.2.0",
    "navigation-react": "^4.1.1",
    "navigation-react-native": "^5.2.1",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.1",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
And the screen on Simulator:

![image](https://user-images.githubusercontent.com/2016484/60755474-cdd7c600-a00d-11e9-9f4b-cdc764124ccd.png)

Even if navigation-react-native updates to officially support `v0.60` I may have to stick to the `v0.59` version since other packages i rely on will also need to be similarly compatible and i don't think that may happen very soon.

**Comment by grahammendick** [comment]
I just released navigation-react-native v5.3.0. It supports React Native v0.60 and is ready whenever you are. No more manual linking. Don’t forget to run `pod install`. See the [set up guide](https://grahammendick.github.io/navigation/documentation/native/setup.html) for the full instructions.
